### ISSUE TITLE
WebExtensionPack2017 break Browser Link due to CSS Tools

### ISSUE THREAD

**Issue by philiphendry** [madskristensen/WebExtensionPack2017#4]
### Installed product versions
- Visual Studio: 2017 RC Enterprise
- This extension: 1.1.5
- CSS Tools: 1.0.11

### Description
I noticed Browser Link Dashboard never showed a connect the the browser link javascript was never delivered to my browser. Eventually I ran a repair on VS2017RC and it started working again. I then installed Web Extension Pack 2017 without having installed anything else - at this point Browser Link Dashboard showed no connections again.

### Steps to recreate (unverified but close to how I came about the problem)
1. Launch clean install of Visual Studio 2017 RC
2. Install Web Extension Pack 2017
3. Run blank Web Application template and noticed Browser Link Dashboard has no connections.
4. Uninstall Web Extension Pack 2017 ( I think this leaves all the other extensions behind)
5. Uninstall CSS Tools extension
6. Run the application again and the Browser Link Dashboard shows a connection again as expected.

I hope I've identified CSS Tools as the cause correctly but if there were any doubt that is why raised this issue here instead of the CSS Tools extension.

**Comment by madskristensen** [comment]
Fixed in latest version of CSS Tools
